version: '3.7'

services:
  frontend:
    image: danyavshivtsev/telegram-web-app
    container_name: telegram-web-app
    ports:
      - 80:80
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
